#!/bin/sh


termite &
# Process ID of the process we just launched
PID=$!
sleep 0.2
ID=$(xdotool search --pid $PID | tail -1)

xdotool windowmove $ID 50 50
xdotool windowsize $ID 600 350


termite &
# Process ID of the process we just launched
PID=$!
sleep 0.2
ID=$(xdotool search --pid $PID | tail -1)

xdotool windowmove $ID 655 50
xdotool windowsize $ID 600 350

termite &
# Process ID of the process we just launched
PID=$!
sleep 0.2
ID=$(xdotool search --pid $PID | tail -1)

xdotool windowmove $ID 50 435 
xdotool windowsize $ID 600 350

termite &
# Process ID of the process we just launched
PID=$!
sleep 0.2
ID=$(xdotool search --pid $PID | tail -1)

xdotool windowmove $ID 655 435 
xdotool windowsize $ID 600 350